import { Arimo } from "next/font/google";
import "./globals.css";

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-arimo",
});


export const metadata = {
  title: "create",
  description: "Generated by service montir",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${arimo.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
